name: okoa
description: "Okoa App. Security in the palm of your hands"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # --------- CORE
  permission_handler: ^11.1.0
  get_it: ^7.6.4
  flutter_native_splash: ^2.3.8

  # --------- Hive Dependency
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # --------- UI
  fluttertoast: ^8.2.4
  sliver_tools: ^0.2.12
  flutter_svg: ^2.0.9
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  supabase_flutter: ^2.0.2
  get: ^4.6.6
  envied: ^0.5.2

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  # hive builder
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  envied_generator: ^0.5.2

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#343a40"
  image: "assets/images/logo.png"
  image_dark: "assets/images/logo.png"
  android_12:
    color: "#ffffff"
    color_dark: "#343a40"
    image: "assets/images/logo.png"
    image_dark: "assets/images/logo.png"
  android: true
  ios: true
  web: false
  fullscreen: true

# Flutter Specific
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
