name: okoa
description: "Okoa App. Security in the palm of your hands"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # --------- CORE
  permission_handler: ^10.4.1
  get_it: ^7.6.4
  flutter_native_splash: ^2.3.8

  # --------- Hive Dependency
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # --------- UI
  fluttertoast: ^8.2.4
  sliver_tools: ^0.2.12
  flutter_svg: ^2.0.9
  image_picker: ^1.0.0
  image_cropper: ^5.0.0

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # hive builder
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#343a40"
  android_12:
    color: "#ffffff"
    color_dark: "#343a40"
  android: true
  ios: true
  web: false
  fullscreen: true

# Flutter Specific
flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
